name: WebdriverIO Visual Regression Tests
on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  wdio-run:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install

      - name: Linter and Prettier
        run: |
          npx eslint --quiet
          npx prettier --check .

      - name: Run WebdriverIO Tests
        run: xvfb-run --auto-servernum npm run wdio -- --env chrome

      - name: Generate Visual Report
        if: always()
        run: npm run report:generate

      - name: Setup Pages
        if: always()
        uses: actions/configure-pages@v5

      - name: Upload WebdriverIO results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: visual-regression-results
          path: visual-report/report
          retention-days: 30

      - name: Deploy to GitHub Pages
        if: always()
        id: deployment
        uses: actions/deploy-pages@v4
